# Docker Compose YAML for kafka library testing
# TODO move kafka and schema-registry to non-standard ports
version: '3.4'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:4.1.0"
    hostname: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32182
  kafka:
    image: "confluentinc/cp-kafka:4.1.0"
    ports:
      - "29092:29092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32182
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
# we may need schema-registry for some sort of avro schema-related support (not sure what exactly).  Fix config
#  schema-registry:
#    image: "confluentinc/cp-schema-registry:4.1.0"
#    ports:
#      - "8081:8081"
#    environment:
#      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:32182
#      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
#      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081